# Created with the winget manifest schema
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Creahive.MultiTaskbar
PackageVersion: 1.4.2
InstallerType: portable
Commands:
- multitaskbar
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Creahive/MultiTaskbar/releases/download/v1.4.2/MultiTaskbar.exe
  InstallerSha256: 13CFF5B2977545B2AD017BAF4072C938E05BC90C2A9D40DC3B470E582761EA43
ManifestType: installer
ManifestVersion: 1.6.0
